server:
  port: ${port:8761}
eureka:
  client:
    fetchRegistry: false
    service-url:
      defaultZone: http://${host:localhost}:${port:8761}/eureka
management:
  security:
    enabled: ${actuator.protected:true}