server:
  port: ${DISCOVERY_PORT:8761}
eureka:
  server:
    renewal-percent-threshold: 0.3
  client:
#   Разрешить дискавери регистрировать самого себя
    registerWithEureka: ${selfRegistred:false}
    fetchRegistry: false
    service-url:
      defaultZone: http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka
management:
  security:
    enabled: ${actuator.protected:true}